name: avatar_filter
description: "Test Project for Zeely"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  skeletonizer: ^2.1.2
  easy_localization: ^3.0.8
  json_annotation: ^4.9.0
  go_router: ^16.2.4
  freezed_annotation: ^3.1.0
  animated_reorderable_list: ^1.3.0
  provider: ^6.1.5+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.7.1
  build_verify: ^3.1.1
  go_router_builder: ^4.1.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lang/
    - assets/icons/
    - assets/images/
    - assets/avatar_mock/
    - assets/data/
    - assets/fonts/

  fonts:
    - family: Italian_Plate_No2_Expanded
      fonts:
        - asset: "assets/fonts/Italian Plate No2 Expanded Thin.ttf"
          weight: 100
        - asset: "assets/fonts/Italian Plate No2 Expanded Thin Italic.ttf"
          weight: 100
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Ultralight.ttf"
          weight: 200
        - asset: "assets/fonts/Italian Plate No2 Expanded Ultralight Italic.ttf"
          weight: 200
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Extralight.ttf"
          weight: 200
        - asset: "assets/fonts/Italian Plate No2 Expanded Extralight Italic.ttf"
          weight: 200
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Light.ttf"
          weight: 300
        - asset: "assets/fonts/Italian Plate No2 Expanded Light Italic.ttf"
          weight: 300
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded.ttf"
          weight: 400
        - asset: "assets/fonts/Italian Plate No2 Expanded Italic.ttf"
          weight: 400
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Italian Plate No2 Expanded Medium Italic.ttf"
          weight: 500
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Demibold.ttf"
          weight: 600
        - asset: "assets/fonts/Italian Plate No2 Expanded Demibold Italic.ttf"
          weight: 600
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Italian Plate No2 Expanded Bold Italic.ttf"
          weight: 700
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Extrabold.ttf"
          weight: 800
        - asset: "assets/fonts/Italian Plate No2 Expanded Extrabold Italic.ttf"
          weight: 800
          style: italic
        - asset: "assets/fonts/Italian Plate No2 Expanded Black.ttf"
          weight: 900
        - asset: "assets/fonts/Italian Plate No2 Expanded Black Italic.ttf"
          weight: 900
          style: italic

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

